// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for generating health-related articles.
 *
 * - generateHealthPost - A function that generates a health article on a given topic.
 * - GenerateHealthPostInput - The input type for the generateHealthPost function.
 * - GenerateHealthPostOutput - The return type for the generateHealthPost function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateHealthPostInputSchema = z.object({
  topic: z.string().describe('The health topic for the article.'),
});
export type GenerateHealthPostInput = z.infer<typeof GenerateHealthPostInputSchema>;

const GenerateHealthPostOutputSchema = z.object({
  title: z.string().describe('The title of the generated article.'),
  content: z.string().describe('The full content of the article, formatted in paragraphs.'),
});
export type GenerateHealthPostOutput = z.infer<typeof GenerateHealthPostOutputSchema>;

export async function generateHealthPost(input: GenerateHealthPostInput): Promise<GenerateHealthPostOutput> {
  return generateHealthPostFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateHealthPostPrompt',
  input: {schema: GenerateHealthPostInputSchema},
  output: {schema: GenerateHealthPostOutputSchema},
  prompt: `You are a health and wellness expert writing for the general public in French. Your goal is to create a clear, informative, and encouraging article about the given topic.

The article should be well-structured, easy to understand, and provide practical advice.

Topic: {{{topic}}}

Instructions:
1.  Create a compelling and clear title for the article.
2.  Write the article content. Start with a brief introduction explaining the importance of the topic.
3.  Develop the main points in several paragraphs. Use simple language.
4.  Include practical tips or a small list of actionable steps.
5.  Conclude with a positive and encouraging summary.
6.  The entire response must be in French.`,
});

const generateHealthPostFlow = ai.defineFlow(
  {
    name: 'generateHealthPostFlow',
    inputSchema: GenerateHealthPostInputSchema,
    outputSchema: GenerateHealthPostOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
