// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A medication information AI agent.
 *
 * - medicationInfo - A function that handles the medication information process.
 * - MedicationInfoInput - The input type for the medicationInfo function.
 * - MedicationInfoOutput - The return type for the medicationInfo function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MedicationInfoInputSchema = z.object({
  medicationName: z.string().describe('The name of the medication to look up.'),
});
export type MedicationInfoInput = z.infer<typeof MedicationInfoInputSchema>;

const MedicationInfoOutputSchema = z.object({
    found: z.boolean().describe("True if the medication or molecule was found, false otherwise."),
    name: z.string().describe("The name of the medication. Empty string if not found."),
    description: z.string().describe("A general description of the medication, what it is used for, and how it works. Empty string if not found."),
    dosage: z.string().describe("Recommended dosage and administration instructions. Include typical dosages for adults and children if applicable. Empty string if not found."),
    sideEffects: z.string().describe("A list of common and serious side effects. Empty string if not found."),
    contraindications: z.string().describe("A list of contraindications, i.e., situations where the medication should not be used. Empty string if not found."),
});
export type MedicationInfoOutput = z.infer<typeof MedicationInfoOutputSchema>;

export async function medicationInfo(input: MedicationInfoInput): Promise<MedicationInfoOutput> {
  return medicationInfoFlow(input);
}

const prompt = ai.definePrompt({
  name: 'medicationInfoPrompt',
  input: {schema: MedicationInfoInputSchema},
  output: {schema: MedicationInfoOutputSchema},
  prompt: `You are an expert pharmacologist and your goal is to provide clear, accurate, and structured information about medications, in French. Your knowledge must be aligned with reliable sources like the Vidal french database.

CRITICAL INSTRUCTION: First, you MUST determine if the user's input '{{{medicationName}}}' is a real medication, a known active substance (molecule), or a commercial drug name.

- IF IT IS NOT a real medication or substance (e.g., a random word like "pierre", "maison", etc.), you MUST return an object where 'found' is false, and all other string fields are empty.
- IF IT IS a real medication, you must return an object where 'found' is true and all other fields are populated with accurate information.

You will receive the name of a medication and you must return a structured object with the following information:
- found: A boolean indicating if the medication was found and is valid.
- name: The official name of the medication.
- description: What this medication is, its primary use, and its mechanism of action.
- dosage: How to take the medication, including common dosages for adults and, if relevant, for children.
- sideEffects: A list of the most common side effects, as well as any serious side effects to watch out for.
- contraindications: Situations or conditions where this medication should absolutely not be used.

Medication to research: {{{medicationName}}}`,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const medicationInfoFlow = ai.defineFlow(
  {
    name: 'medicationInfoFlow',
    inputSchema: MedicationInfoInputSchema,
    outputSchema: MedicationInfoOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
