-- =================================================================
--          SCRIPT DE CONFIGURATION DE LA BASE DE DONNÉES
-- =================================================================
-- Ce script configure les tables et les politiques de sécurité
-- nécessaires pour la fonctionnalité de recherche de produits.

-- -----------------------------------------------------------------
-- TABLE 1: profiles
-- Stocke les informations des utilisateurs (clients et pharmaciens).
-- -----------------------------------------------------------------
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text NOT NULL,
  phone text UNIQUE,
  role text NOT NULL CHECK (role IN ('Client', 'Pharmacien')),
  pharmacy_name text,
  updated_at timestamptz,
  CONSTRAINT username_length CHECK (char_length(username) >= 2)
);

-- RLS policies for profiles table
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Les utilisateurs peuvent voir leur propre profil.
CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

-- Les utilisateurs peuvent mettre à jour leur propre profil.
CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Les utilisateurs connectés peuvent voir les profils des pharmaciens.
CREATE POLICY "Authenticated users can see pharmacists profiles" ON public.profiles
  FOR SELECT TO authenticated USING (role = 'Pharmacien');


-- -----------------------------------------------------------------
-- TABLE 2: searches
-- Stocke les demandes de recherche de produits initiées par les clients.
-- -----------------------------------------------------------------
CREATE TABLE public.searches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  original_product_name text,
  product_name text NOT NULL,
  photo_urls text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending' -- pending, answered, closed
);

-- RLS policies for searches table
ALTER TABLE public.searches ENABLE ROW LEVEL SECURITY;

-- Les clients peuvent voir leurs propres demandes.
CREATE POLICY "Clients can view their own searches" ON public.searches
  FOR SELECT USING (auth.uid() = client_id);

-- Les clients peuvent créer des demandes.
CREATE POLICY "Clients can create searches" ON public.searches
  FOR INSERT WITH CHECK (auth.uid() = client_id);

-- Les pharmaciens peuvent voir toutes les demandes.
CREATE POLICY "Pharmacists can view all searches" ON public.searches
  FOR SELECT USING ( (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Pharmacien' );


-- -----------------------------------------------------------------
-- TABLE 3: responses
-- Stocke les réponses des pharmaciens aux demandes de recherche.
-- -----------------------------------------------------------------
CREATE TABLE public.responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_id bigint NOT NULL REFERENCES public.searches(id) ON DELETE CASCADE,
  pharmacist_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  pharmacy_name text NOT NULL,
  price text,
  available boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS policies for responses table
ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;

-- Les pharmaciens peuvent créer des réponses.
CREATE POLICY "Pharmacists can create responses" ON public.responses
  FOR INSERT WITH CHECK ( (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'Pharmacien' AND auth.uid() = pharmacist_id );

-- Les pharmaciens peuvent voir leurs propres réponses.
CREATE POLICY "Pharmacists can view their own responses" ON public.responses
  FOR SELECT USING (auth.uid() = pharmacist_id);

-- Les clients peuvent voir les réponses à leurs propres demandes.
CREATE POLICY "Clients can see responses to their searches" ON public.responses
  FOR SELECT USING (
    search_id IN (SELECT id FROM public.searches WHERE client_id = auth.uid())
  );


-- -----------------------------------------------------------------
-- TABLE 4: messages
-- Stocke les messages de chat entre un client et un pharmacien pour une recherche.
-- -----------------------------------------------------------------
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_id bigint NOT NULL REFERENCES public.searches(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS policies for messages table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Les utilisateurs peuvent envoyer des messages dans une conversation à laquelle ils participent.
CREATE POLICY "Users can send messages in their conversations" ON public.messages
  FOR INSERT WITH CHECK (
    auth.uid() = sender_id AND
    (
      -- Soit le client de la recherche
      auth.uid() IN (SELECT client_id FROM public.searches WHERE id = search_id) OR
      -- Soit un pharmacien qui a répondu
      auth.uid() IN (SELECT pharmacist_id FROM public.responses WHERE search_id = messages.search_id)
    )
  );

-- Les utilisateurs peuvent voir les messages des conversations auxquelles ils participent.
CREATE POLICY "Users can view messages in their conversations" ON public.messages
  FOR SELECT USING (
    (
      -- Soit le client de la recherche
      auth.uid() IN (SELECT client_id FROM public.searches WHERE id = search_id) OR
      -- Soit un pharmacien qui a répondu
      auth.uid() IN (SELECT pharmacist_id FROM public.responses WHERE search_id = messages.search_id)
    )
  );


-- -----------------------------------------------------------------
-- STORAGE BUCKET: demands
-- Pour stocker les images des demandes de produits.
-- -----------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('demands', 'demands', true)
ON CONFLICT (id) DO NOTHING;

-- RLS Policies for demands storage bucket
-- Permet aux utilisateurs authentifiés de voir les images.
CREATE POLICY "Authenticated users can view demand images"
ON storage.objects FOR SELECT
TO authenticated
USING ( bucket_id = 'demands' );

-- Permet aux utilisateurs de téléverser des images dans un dossier correspondant à leur ID.
CREATE POLICY "Users can upload to their own folder"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'demands' AND (storage.foldername(name))[1] = auth.uid()::text );


-- =================================================================
--                 FIN DU SCRIPT DE CONFIGURATION
-- =================================================================
